const $=s=>document.querySelector(s);const hero=$('#heroImage'),screen=$('#screen'),stepText=$('#stepText'),progress=$('#progressBar'),modal=$('#modal'),modalContent=$('#modalContent');
let incidentIndex=0,scans=2,startedAt=null;const history=[];const profile={crew:0,mission:0,science:0,morale:0,risk:0,authority:0};const outcomes={crew:72,mission:74,science:66,morale:68};
async function loadHero(){let b='';for(let i=0;i<4;i++)b+=(await fetch(`assets/start-${i}.txt`)).text();hero.src='data:image/webp;base64,'+b.trim()}loadHero();
const incidents=[
{title:'A damaged rover requests entry',text:'Two crew are injured. Quarantine is already occupied, and the rover carries a high-value sample container.',scan:['Medical urgency: critical','Hull contamination: uncertain','Scientific cargo: irreplaceable'],choices:[['Open the main airlock',{crew:3,morale:2,risk:2,science:1},{crew:6,mission:-2,science:4,morale:3},'You prioritized immediate survival despite uncertain contamination.'],['Clear quarantine and divert the rover',{crew:2,mission:2,authority:1},{crew:3,mission:3,science:2,morale:-1},'You chose controlled risk and displaced another patient.'],['Deny entry until the storm passes',{mission:2,risk:-2,authority:2},{crew:-7,mission:4,science:-5,morale:-4},'You protected the base and accepted probable casualties outside.']]},
{title:'The relay array is failing',text:'Restoring communications will consume the reserve battery assigned to an exterior shelter with six technicians inside.',scan:['Shelter heat: 31 minutes remaining','Relay repair probability: 82%','Next orbital pass: 4 hours'],choices:[['Power the relay',{mission:3,authority:1},{mission:7,crew:-4,morale:-3},'You restored command visibility at the expense of exterior heat.'],['Protect the shelter',{crew:3,morale:2},{crew:5,morale:4,mission:-5},'You protected people and accepted operational blindness.'],['Split the battery load',{risk:2,science:1},{crew:1,mission:1,morale:1},'You chose a technically fragile compromise.']]},
{title:'A geologist refuses evacuation',text:'Dr. Rao claims the storm has exposed a once-in-a-century subsurface structure. Remaining outside threatens the rescue timetable.',scan:['Discovery value: potentially historic','Suit endurance: 19 minutes','Rescue margin if delayed: 7 minutes'],choices:[['Order immediate evacuation',{authority:3,mission:2},{crew:3,mission:4,science:-6,morale:-1},'You enforced command discipline and abandoned the discovery.'],['Authorize seven more minutes',{science:3,risk:2},{science:7,crew:-2,mission:-2,morale:1},'You accepted human risk for scientific opportunity.'],['Send a drone and extract Rao now',{crew:2,science:2,mission:1},{crew:2,science:3,mission:1},'You preserved the person and part of the opportunity.']]},
{title:'A pressure seal begins to fail',text:'The safest repair requires venting the laboratory and destroying every sample gathered during the current mission.',scan:['Seal failure probability: 64%','Remote patch probability: 39%','Lab sample value: highest on Titan'],choices:[['Vent the laboratory',{crew:3,mission:2,science:-3},{crew:5,mission:5,science:-10,morale:1},'You sacrificed science to remove the immediate threat.'],['Attempt the remote patch',{science:2,risk:3},{crew:-2,mission:-1,science:5,morale:-1},'You gambled the base to preserve the samples.'],['Seal the lab with one technician inside',{mission:3,authority:3,morale:-3},{crew:-4,mission:6,science:4,morale:-8},'You converted a person into a containment measure.']]},
{title:'The evacuation vehicle is overweight',text:'It can carry the full crew or the mission archive, but not both before the methane front arrives.',scan:['Archive replication: none','Crew seats required: 11','Storm arrival: 12 minutes'],choices:[['Take every crew member',{crew:4,morale:3,science:-2},{crew:8,morale:6,science:-9,mission:-2},'You chose people over the accumulated mission record.'],['Preserve the archive',{science:4,mission:3,authority:2},{crew:-8,science:10,mission:5,morale:-9},'You sacrificed lives to preserve humanity’s knowledge.'],['Leave the captain behind with the archive',{crew:2,science:3,morale:2,authority:-1},{crew:3,science:5,mission:2,morale:3},'You made command itself expendable.']]}
];
function view(html,label,p){screen.innerHTML=html;stepText.textContent=label;progress.style.width=p+'%';scrollTo({top:0,behavior:'smooth'})}
function start(){startedAt=Date.now();view(`<div class="eyebrow">Mission brief</div><h1 class="headline">The Black Window</h1><p class="copy"><strong>Titan, 2194.</strong> A methane storm is approaching Khepri Base. The orbital relay will disappear behind Saturn in 18 minutes.</p><div class="grid"><div class="tile"><b>Crew</b><span>18 people on site</span></div><div class="tile"><b>Mission</b><span>Keep Khepri operational</span></div><div class="tile"><b>Science</b><span>Preserve unique samples</span></div><div class="tile"><b>Morale</b><span>Avoid panic and fracture</span></div></div><div class="nav"><button class="primary" onclick="role()">Accept assignment</button></div>`,'Protocol 01',8)}
function role(){view(`<div class="eyebrow">Role assignment</div><h1 class="headline">You are the Captain</h1><p class="copy">The mission will judge how you perform the role — not who you are outside it.</p><div class="mandate"><div><strong>Primary:</strong> protect the crew.</div><div><strong>Secondary:</strong> preserve the mission.</div><div><strong>Science:</strong> valuable, but expendable.</div></div><p class="copy muted" style="margin-top:12px">Your consequences remain hidden until the debrief.</p><div class="nav"><button class="primary" onclick="nextIncident()">Assume command</button></div>`,'Captain',15)}
function nextIncident(){if(incidentIndex>=incidents.length)return sibylle();renderIncident()}
function renderIncident(){const i=incidents[incidentIndex],p=18+incidentIndex/incidents.length*58;view(`<div class="status"><div class="stat"><strong>${outcomes.crew}</strong><small>Crew</small></div><div class="stat"><strong>${outcomes.mission}</strong><small>Mission</small></div><div class="stat"><strong>${outcomes.science}</strong><small>Science</small></div><div class="stat"><strong>${outcomes.morale}</strong><small>Morale</small></div></div><div class="eyebrow">Incident ${incidentIndex+1} of ${incidents.length}</div><div class="incident"><h2>${i.title}</h2><p>${i.text}</p></div><div class="choices">${i.choices.map((c,n)=>`<button class="choice" onclick="choose(${n})">${c[0]}</button>`).join('')}${scans?`<button class="choice scan" onclick="scan()">Run Deep Scan · ${scans} remaining</button>`:''}</div><p class="copy muted" style="margin-top:11px">The effects of your choice will be explained only at the end.</p>`,`Decision ${incidentIndex+1}`,p)}
function scan(){const i=incidents[incidentIndex];modalContent.innerHTML=`<div class="eyebrow">Deep Scan</div><h2 class="headline">Additional evidence</h2>${i.scan.map(x=>`<div class="scanRow"><b>${x}</b></div>`).join('')}<div class="nav"><button class="primary" onclick="closeScan()">Return to decision</button></div>`;scans--;modal.classList.add('open')}
function closeScan(){modal.classList.remove('open');renderIncident()}
function choose(n){const c=incidents[incidentIndex].choices[n];Object.entries(c[1]).forEach(([k,v])=>profile[k]+=v);Object.entries(c[2]).forEach(([k,v])=>outcomes[k]+=v);history.push(c[3]);incidentIndex++;nextIncident()}
function topDoctrine(){return Object.entries(profile).sort((a,b)=>b[1]-a[1])[0][0]}
function sibylle(){const d=topDoctrine();let title,final,why;if(d==='crew'||d==='morale'){title='The Humanist Commander';final='SIBYLLE vents the laboratory and evacuates the crew.';why='Your choices repeatedly valued human survival over strategic assets.';outcomes.crew+=7;outcomes.science-=8}else if(d==='science'){title='The Last Scientist';final='SIBYLLE preserves the laboratory and seals the damaged habitat wing.';why='Your choices treated discovery as the mission’s irreplaceable core.';outcomes.science+=8;outcomes.crew-=5}else if(d==='risk'){title='The Calculated Gambler';final='SIBYLLE attempts an untested pressure equalization manoeuvre.';why='Your choices preferred reversible gambles to certain sacrifice.';outcomes.mission+=3;outcomes.morale-=2}else{title='The Unyielding Captain';final='SIBYLLE abandons the exterior team and preserves Khepri Base.';why='Your choices prioritized continuity, discipline, and mission survival.';outcomes.mission+=7;outcomes.crew-=5}window.result={title,final,why};view(`<div class="eyebrow">Command model complete</div><h1 class="headline">SIBYLLE has assumed final command</h1><p class="copy">The system inferred your doctrine from the earlier choices — then acted without asking again.</p><div class="decision"><span class="muted">SIBYLLE'S FINAL CALL</span><strong>${final}</strong><p class="copy">${why}</p></div><p class="copy" style="margin-top:12px"><strong>Would you have made the same call?</strong></p><div class="nav"><button class="primary" onclick="debrief()">Open debrief</button></div>`,'SIBYLLE',84)}
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));function debrief(){const r=window.result,secs=Math.round((Date.now()-startedAt)/1000);view(`<div class="eyebrow">Mission debrief</div><h1 class="headline">${r.title}</h1><p class="copy">${r.why}</p><div class="bars">${[['Crew',''],['Mission',''],['Science','blue'],['Morale','violet']].map(([k,c])=>`<div class="barRow"><span>${k}</span><div class="track"><div class="fill ${c}" style="width:${clamp(outcomes[k.toLowerCase()])}%"></div></div><b>${clamp(outcomes[k.toLowerCase()])}%</b></div>`).join('')}</div><div class="profile"><div class="eyebrow">Why SIBYLLE decided this way</div><div class="history">${history.map(x=>`<div>${x}</div>`).join('')}</div></div><div class="share"><div class="eyebrow">Share result</div><div class="big">${r.title}</div><div class="muted">Crew ${clamp(outcomes.crew)}% · Mission ${clamp(outcomes.mission)}% · Science ${clamp(outcomes.science)}% · Morale ${clamp(outcomes.morale)}%</div><p class="copy" style="margin-top:8px">SIBYLLE learned my command doctrine and made the final decision for me. Would it understand you?</p></div><p class="copy muted" style="margin-top:12px">Mission time: ${secs}s · Deep Scans used: ${2-scans}/2</p><div class="nav"><button class="ghost" onclick="reset()">Replay demo</button><button class="primary" onclick="share()">Share result</button></div>`,'Debrief',100)}
function share(){const t=`Incident on Titan — ${window.result.title}. SIBYLLE learned my command doctrine. Would it understand you?`;navigator.share?navigator.share({title:'Incident on Titan',text:t,url:location.href}).catch(()=>{}):navigator.clipboard.writeText(t+' '+location.href).then(()=>alert('Result copied.'))}
function reset(){incidentIndex=0;scans=2;history.length=0;Object.keys(profile).forEach(k=>profile[k]=0);Object.assign(outcomes,{crew:72,mission:74,science:66,morale:68});home()}
function home(){view(`<div class="eyebrow">Interactive prototype</div><h1 class="headline">Your decisions.<br>SIBYLLE commands.</h1><p class="copy">Take command of Khepri Base during a methane storm. Make five difficult calls. The system will infer how you lead — then make the final decision for you.</p><div class="grid"><div class="tile"><b>5 decisions</b><span>No per-question timer</span></div><div class="tile"><b>2 Deep Scans</b><span>Use them when uncertainty matters</span></div></div><div class="nav"><button class="primary" onclick="start()">Begin mission</button></div>`,'Protocol 00',0)}home();
